name: deploying Hexo project to GitHub pages

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and Deploy
        uses: theme-keep/hexo-deploy-github-pages-action@master
        env:
          PERSONAL_TOKEN: ${{ secrets.SNEAKYDOG_GITHUB_PAGES_TOKEN }}
          PUBLISH_REPOSITORY: Sneakydog-dmeo/sneakydog-demo.github.io
          BRANCH: gh-pages
          PUBLISH_DIR: ./public
